name: "Test"
on: [push]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Export org files
        uses: tecosaur/org-knit-action@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
